"""
Our MAPPAGRAM application used to show our results and to allow
    the user to generate elevation maps with desired
    conditions
Functions:
    erase(): cleans the file were images are saved
    home(): defines RESULTATS page
    biblio(): calls our RESULTATS page
    theorie(): calls our BIBLIOGRAPHIE page

Run MAPAGRAM.run(debug=True) with argument "debug=True" if you want to modify the app,
    detect errors and see the result without restarting the script
"""
from os import listdir, remove, makedirs, path
from flask import Flask, render_template, request
from generation import save_data

IMG_PATH = './static/images'
MAPAGRAM = Flask(__name__)
IMG_NB = 0


def erase():
    """
    clean the file where old images generated by the Generator were saved
        to be displayed on the website page "image.html" last time
    this fonction is call each time the app is run again
    """
    if not path.exists(IMG_PATH):
        makedirs(IMG_PATH)
    for filename in listdir('./static/images'):
        remove('./static/images' + '/' + filename)


@MAPAGRAM.route('/home', methods=['GET', 'POST'])
def home():
    """
    when the user arrives on the address defined by the route above,
        home() is called and displays the vue
    each new map is generated and saved in the file "static/images"
        thanks to "save_data" function
    RETURN:
        this function return the vue to display when going on the route address
        * the "RESULTATS" page is where a form is displayed asking the values
        of conditions the user wants for the generation
        * when this form is submited, a new page is charged where the map generated
        is displayed and the addresses of the saved images and value of the probability
        that the image generated is "true" are sent to the page
    """
    if request.method == 'POST':
        global IMG_NB
        h_max = request.form.get('h_max')
        h_mean = request.form.get('h_mean')
        if h_max < h_mean:
            memory = h_max
            h_max = h_mean
            h_mean = memory
        proba_real = save_data(IMG_NB+1, int(h_max), int(h_mean))
        path1 = '/static/images/img_{}.png'.format(str(IMG_NB+1))
        path2 = '"/static/images/img_{}.png"'.format(str(IMG_NB+2))
        IMG_NB += 2
        return render_template('image.html', path_img1=path1,
                               path_img2=path2, p_true=str(proba_real))
    return render_template('main_page.html')


@MAPAGRAM.route('/biblio')
def biblio():
    """
    when the user arrives on the address defined by the route above, biblio() is called
        and displays the BIBLIOGRAPHIE vue
    RETURN:
        the page displayed includes interesting links and sources that were usefull
        during the project
    """
    return render_template("bibliographie.html")


@MAPAGRAM.route('/theorie')
def theorie():
    """
    when the user arrives on the address defined by the route above, theorie() is called
        and displays the THEORIE vue
    RETURN:
        the page displayed includes our report where the user will find all the explanations
        and the different steps of our work
    """
    return render_template('theorie.html')


if __name__ == '__main__':
    erase()
    MAPAGRAM.run()
